### ISSUE TITLE
[5pt] Retrieve USGS ahps datasets

### ISSUE THREAD

**Issue by TrevorGrout-NOAA** [NOAA-OWP/cahaba#109]
In preparation of ahps analysis get USGS datasets available. Coordinate with Katherine and USGS as necessary. Download grid and polygon and keep track of data issues and reach out to USGS for assistance resolving.

This is a subtask to #91

**Comment by BradfordBates-NOAA** [comment]
Completed for this Sprint. If USGS post new data, we will open a new card to track its acquisition.
