### ISSUE TITLE
[21pt] Learning how to run the FIM 3 on VM and reviewing the related documents about FIMs.

### ISSUE THREAD

**Issue by ChristyWestcott-NOAA** [NOAA-OWP/cahaba#157]

**Comment by BradfordBates-NOAA** [comment]
@HamedZamanisabzi-NOAA Please see this document: https://docs.google.com/document/d/1gFIVwwpfpyiJZ_2AubSgtJXd5CzblEA5zogCJjWfF6g/edit#heading=h.suyvqiyp1iu6
