### ISSUE TITLE
[3pt] Use DEM raster to determine projection of FIM outputs

### ISSUE THREAD

**Issue by BrianAvant-NOAA** [NOAA-OWP/cahaba#168]
Use DEM raster to determine projection of FIM outputs

## Current behavior
It may not make sense to project HI and PR HUCs in `USA_Contiguous_Albers_Equal_Area_Conic_USGS_version`. Using the projection of the DEM raster, we can use an appropriate projection for our FIM outputs.

The outputs of the SRCs will need to be reviewed before making this change.

**Comment by BradfordBates-NOAA** [comment]
@BrianAvant-NOAA Is this still relevant?
