### ISSUE TITLE
[2pt] MS X-Walk Issue at Fort Hunter, NY

### ISSUE THREAD

**Issue by frsalas-noaa** [NOAA-OWP/cahaba#170]
## Current behavior

FIM v2.X MS capability at Fort Hunter, NY has bug in crosswalk from NWM reach to MS reach. Blue in figure below is RnR FIM forecast and there is a gap along reach 13637. In crosswalk table it shows reach 13637 pulling flow from the NWM reach along 13286 (TSID 22745931 is the NWM feature_id along 13286).

![image](https://user-images.githubusercontent.com/62669859/102434369-3e905980-3fda-11eb-965d-52a84fc34a68.png)

## Expected behavior

Expect TSID at 13637 to be 3249000.

Suggest checking if FIM v3.0 has same issue at this location. If so, implement fix by either providing mechanism to override x-walk algorithm when needed or update x-walk so that it is more robust at junctions like this.

**Comment by frsalas-noaa** [comment]
If this gap does not exist in FIM v3.0, please provide @LauraKeys-NOAA and Katherine Powell with FIM v3.0 MS datasets so we can rerun RnR FIM in this area. If gap does exist in FIM v3.0, please address and provide data.

Would like to regenerate RnR FIMs in January and deliver to NERFC to support APG tabletop activities.

**Comment by LauraKeys-NOAA** [comment]
More specific info about where the gap is? Fort Hunter's crosswalk appears
fine when I run a high flows scenario, but perhaps you're talking about the
Sacandaga River north of Fort Hunter by the lake?

**Comment by LauraKeys-NOAA** [comment]
(sorry, ignore last comment.. I didn't realize there was earlier context provided!)

**Comment by BrianAvant-NOAA** [comment]
It is helpful to the dev team to provide the HUC8 with these tickets as well.

**Comment by BrianAvant-NOAA** [comment]
This area is right at the boundary of two HUC8s so I provided FIM v3.0 outputs for both in `T:\temp\laura.keys\fim3_examples`.

**Comment by frsalas-noaa** [comment]
Thanks for looking into this. Would like to target providing NERFC with new RnR FIMs for APG tabletop events in NY. Will include HUC unit in future.

**Comment by LauraKeys-NOAA** [comment]
I have a script prepared that can create the FIM3 outputs for that area and
am working on adding all our inundation attributes to the final polygon
result. Will work with Katherine to have her generate the new RNR output.

**Comment by KatherinePowell-NOAA** [comment]
Update: Laura and I will talk Thursday about this...

**Comment by KatherinePowell-NOAA** [comment]
I have created a new set of ArcGIS Shapefiles for Fort Hunter, NY and surrounding area - R&R 5-Day inundation forecast using FIM 3.0. They are available here:

\\nwcal-fs2.nwc.nws.noaa.gov\GID\activities\fy_20_21_apg\nerfc_case_studies\data\shapes\FortHunterNY_rnr_FIM3

Here is a snapshot of the area with the Aug 27, 2011 0Z forecast:

![image](https://user-images.githubusercontent.com/76983310/104742477-177b9380-5710-11eb-9277-5ccd0a39fc1d.png)

Let me know if I should create the entire regional FIMs in this way...

**Comment by KatherinePowell-NOAA** [comment]
Here's a better map of the two RnR FIMs. The Aug 27 2011 0Z forecast is shown for both... dark areas are the prior (FIM 2.x) version of the forecast map, and lighter blue is the new (FIM 3) FIM shapefile:

![image](https://user-images.githubusercontent.com/76983310/104746420-e0f44780-5714-11eb-920e-dc3fb49e4339.png)

**Comment by KatherinePowell-NOAA** [comment]
NOTE: The lighter blue (FIM 3.0) extends in some of the same areas as the prior (FIM 2.x) forecast - it just looks darker because that layer is under the dark areas...

**Comment by LauraKeys-NOAA** [comment]
@BrianAvant-NOAA could you please provide additional huc8 datasets for 02020006, 02020007 and 02020008 in the same folder on the t drive as with the previous ones?

**Comment by BrianAvant-NOAA** [comment]
@LauraKeys-NOAA will do.

**Comment by KatherinePowell-NOAA** [comment]
Update - the full NY event RnR FIMs were recreated using the FIM 3.0 - I'm working with Whitney in WPOD on Thursday 1/21 to distribute.

**Comment by BrianAvant-NOAA** [comment]
I put the latest version in `fim_3_0_2_0`
