### ISSUE TITLE
[2pt] Replace raster.py with rasterio package

### ISSUE THREAD

**Issue by fernando-aristizabal** [NOAA-OWP/cahaba#18]
Rasterio can now perform all of the functions of raster.py. This goal of this task is to replace usage of raster.py in the FIM workflow with rasterio methods.

**Comment by RyanMcCarthy-NOAA** [comment]
@fernando-aristizabal I didn't get a chance to complete this, but I think most of the work was already done.

**Comment by BrianAvant-NOAA** [comment]
existing fb to resolve this ticket `dev-raster-to-rasterio`
