### ISSUE TITLE
[3pt] Provide feedback for NWS LID static libraries

### ISSUE THREAD

**Issue by TrevorGrout-NOAA** [NOAA-OWP/cahaba#190]
Perform reviews on NWS LID static libraries. Provide feedback on potential mapping issues.

https://dev-gis.nwc.nws.noaa.gov/portal/home/webmap/viewer.html?webmap=c138f115f0744796a1feb189c54d3895

**Comment by BradfordBates-NOAA** [comment]
@LauraKeys-NOAA Please add feedback here.

**Comment by LauraKeys-NOAA** [comment]
I looked at a random site in southeast Iowa on the Skunk River near Augusta and the Iowa/Illinois border (gage ID AGSI4) and found that the action and minor mappings in the static service appear to be the same, but according to data in water.weather.gov for that site, the action and minor stages have 1 foot of difference:
Major Flood Stage: 20
Moderate Flood Stage: 17
Flood Stage: 15
Action Stage: 14

I was curious what the flows were coming out of wrds for these different stages and what heights get mapped for those flows based on the FIM3 rating curves.

**Comment by BradfordBates-NOAA** [comment]
I think this is a bug. I see that action and minor have the same extent everywhere, not just in this location. Let's make sure we're passing the right flows into the flow files. I also remember there was an issue with the filenames at one point too.

**Comment by BradfordBates-NOAA** [comment]
Checked one of the flow files--looks good.  I think this is occurring in post-processing.

**Comment by RyanSpies-NOAA** [comment]
I noticed the FIM extents look funky all along the River Raison in southeast Michigan. Splotchy inundation in the floodplain and the channel inundation looks like it's limited to the thalweg pixel in many areas. Screenshot from near Petersburg, MI: 
![ahps_fim_feedback](https://user-images.githubusercontent.com/69868854/104487396-a8c4fb80-5592-11eb-951a-4b2e9d67b8b3.png)

**Comment by frsalas-noaa** [comment]
FYI HTST2 action extent extending beyond the major extent

![image](https://user-images.githubusercontent.com/62669859/104503273-745b3a80-55a6-11eb-8a02-1899b2dbd600.png)

**Comment by TrevorGrout-NOAA** [comment]
@frsalas-noaa This is interesting a quick inspection shows the input flow files have action flow << major flow.

**Comment by BradfordBates-NOAA** [comment]
I see that there are three sites in this area, each with very different Qs for action (brlt2, htst2, kmst2). The site with the highest Q (htst2) shows the the source is USGS Ratings Depot. Its Q is considerably larger than the other sites'. See screenshot with attribute table.

![image](https://user-images.githubusercontent.com/69594899/104504859-b1c0c780-55a8-11eb-8cb5-fe8772d2ae50.png)

**Comment by frsalas-noaa** [comment]
CTVG1 near Cartersville, GA has similar behavior as HTST2

![image](https://user-images.githubusercontent.com/62669859/104505347-5a6f2700-55a9-11eb-8e42-fc5205318ddf.png)

**Comment by BradfordBates-NOAA** [comment]
For the location near Cartersville, GA, there are two sites present: CTVG1 and CVLG1. CTVG1 has an action stage of 16ft and CVLG1 has an action stage of 840ft. Trevor confirmed that the WRDS API is reporting the 840ft feet value for CVLG1.

![Uploading image.png…]()

**Comment by BradfordBates-NOAA** [comment]
https://water.weather.gov/ahps/download.php
filter out status values that say "not_defined"
