### ISSUE TITLE
[2pt] Walk Upstream and Downstream NWM segments in HI/PR

### ISSUE THREAD

**Issue by TrevorGrout-NOAA** [NOAA-OWP/cahaba#191]
Upstream and downstream walk of NWM segments in HI/PR. CONUS uses the WRDS location API. Maybe utilize Nick for this.

**Comment by BradfordBates-NOAA** [comment]
@TrevorGrout-NOAA Could you please comment on the status of this issue?

**Comment by TrevorGrout-NOAA** [comment]
Will go ahead and close this as the script has this functionality but WRDS doesn't support yet because it doesn't walk upstream/downstream NWM segments in PR/VI/HI at this time. When WRDS is updated to include these areas the script should work similar to how it works for CONUS.  If there are issues, will open new ticket in github.
