### ISSUE TITLE
[3pt] Possible R&R FIM issue at GLDN7 (Vlab #86744)

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/cahaba#209]
Noted discrepancy between NWM R&R FIM based on peak RFC forecast flow of 15k cfs (stage 22ft) and the North Carolina EM FIMAN scenario for the same peak flood stage (22ft). The FIMAN shows inundation of Ferry Bridge Rd and the R&R based FIM does not. Confirmed in person that a large stretch of Ferry Bridge Rd was indeed closed. Attached FIM and photos.

https://vlab.ncep.noaa.gov/redmine/issues/86744

**Comment by BradfordBates-NOAA** [comment]
Appears to be rating curve issue on the southern incoming stream:, but let's investigate.

![image](https://user-images.githubusercontent.com/69594899/104464293-62fb3980-5578-11eb-91fc-694adbd9a359.png)

**Comment by BradfordBates-NOAA** [comment]
See Vlab ticket for attached Powerpoint presentation

**Comment by RyanSpies-NOAA** [comment]
FIM 3_0_15_0 flood extent for 15kcfs --> 
![image](https://user-images.githubusercontent.com/69868854/114733687-3090e200-9d09-11eb-8aec-70e9465aaa52.png)

**Comment by BradfordBates-NOAA** [comment]
It appears the same behavior occurs in FIM3, and the solution would be to have an improved rating curve for this location. Because this feedback is specific to FIM2, I have labeled this issue as "wontfix".

**Comment by RyanSpies-NOAA** [comment]
Nearby USGS 02089000 (this is also GLDN7 the AHPS location) --> 
![image](https://user-images.githubusercontent.com/69868854/114738813-efe79780-9d0d-11eb-92a3-fc5000206910.png)

The rating curve comparison between FIM 3.0.15.0 and the USGS gage rating looks to be in good agreement at the gage location --> 
![image](https://user-images.githubusercontent.com/69868854/114740068-1e19a700-9d0f-11eb-99c1-bc483efd3a57.png)
