### ISSUE TITLE
[3pt] Investigate FIM v2.X inundation near SeaTac Airport

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/cahaba#211]
From Michael Ryan: Was looking at FIM in the Pac NW this evening and I noticed what may be another area where the R&R is significantly overdoing inundation. This is near Kent, WA - southeast of SeaTac airport, along the Green River. NWM MRF FIM for the same area shows no inundation. This seems similar to what was noticed in Portland, OR a couple weeks ago where large areas of the city were flooded, so I wanted to document it here.

![image](https://user-images.githubusercontent.com/69594899/104495529-7cfb4300-559d-11eb-8977-c58deda21488.png)

**Comment by GregCocks-NOAA** [comment]
I did a lot of the work in a GIS sense on the 3rd Runway expansion back in the early 00s, including utilising early LiDAR data from the Puget Sound LiDAR Consortium; interesting to see this terrain again...
