### ISSUE TITLE
[3pt] JTTI - Manning's n estimates

### ISSUE THREAD

**Issue by fernando-aristizabal** [NOAA-OWP/cahaba#22]
Investigate utility of JTTI manning's n estimates and incorporate support for this dataset if useful.

**Comment by BrianAvant-NOAA** [comment]
@frsalas-noaa is this task still relevant?

**Comment by frsalas-noaa** [comment]
I'd say this is overcome by events. Let's focus on our own calibrating strategy for N until we can unify the NWM and FIM hydrofabrics. Closing issue and we can revisit later if it makes sense.
