### ISSUE TITLE
[3pt] Testing bug with ocean water body masking for huc 18070101

### ISSUE THREAD

**Issue by RyanSpies-NOAA** [NOAA-OWP/cahaba#234]
Issue we are seeing near Ventura, CA:
![image](https://user-images.githubusercontent.com/69868854/106014829-7c75a880-6083-11eb-98bc-8c7771fc385a.png)

Ocean polygon should be masking this:
![image (1)](https://user-images.githubusercontent.com/69868854/106014900-8c8d8800-6083-11eb-825e-2f495491dd0a.png)

**Comment by RyanSpies-NOAA** [comment]
This is lid vrvc1 - https://water.weather.gov/ahps2/hydrograph.php?gage=vrvc1&wfo=lox

**Comment by RyanSpies-NOAA** [comment]
It appears that the gw-catchments_reaches_filtered_addAttribute_crosswalked includes a subcatchment over the ocean. This is causing inundation.py to produce inundation extent over the ocean area despite having nodata values in the rem_zero_masked.tif --> 
![image](https://user-images.githubusercontent.com/69868854/106162045-456bc980-614d-11eb-9b8c-65966a5b0ce5.png)

**Comment by RyanSpies-NOAA** [comment]
We may be able to resolve this issue with #185

**Comment by BradfordBates-NOAA** [comment]
@RyanSpies-NOAA Make a card, if necessary (or use #185), to solve this bug.
