### ISSUE TITLE
[3pt] East Fork of Carson River Showing Significant inundation with very low flows (Vlab #87308)

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/cahaba#237]
From Tim Bardsley:

"Hi, The East Fork of the Carson River nr Gardnerville NV (USGS 10309000) has been flowing well below median, and the RFC has steady flow for the 5 day forecast, but the 5 day replace and route max inundation extent has some roads and neighborhoods impacted."

Reference [Vlab Ticket](https://vlab.ncep.noaa.gov/redmine/issues/87308#change-466899) for screenshots.

**Comment by RyanSpies-NOAA** [comment]
HUC: 16050201
Some NWM featureids: 8920165, 8920193, 8921831, 8921899, 8921907

![image](https://user-images.githubusercontent.com/69868854/106317519-09f7fa80-6234-11eb-9be7-55570842727c.png)
![image](https://user-images.githubusercontent.com/69868854/106317804-71ae4580-6234-11eb-84f4-01c2224e6eae.png)

**Comment by RyanSpies-NOAA** [comment]
I produced the FIM 3.0.0.3 MS (calb) outputs for this area using the flows from the NWM RnR flows copied from WaterView on 1/29/21. The FIM3 results look very similar to those in FIM2. Likely causes for the over-estimation are missing bathy and large Manning's n.

![image](https://user-images.githubusercontent.com/69868854/106320324-59402a00-6238-11eb-8c5c-5e20d2fb3e4b.png)

**Comment by BradfordBates-NOAA** [comment]
Nice find, Ryan. I've added you as the assignee on Vlab. Feel free to respond to Tim when ready.

**Comment by RyanSpies-NOAA** [comment]
![rating_curve_comparison_10310407](https://user-images.githubusercontent.com/69868854/109324165-e9629680-7819-11eb-8807-8dd019b61fef.png)

**Comment by RyanSpies-NOAA** [comment]
This issues addressed in this card are slated to be addressed by: #32 (bathymetry prototype solutions), #116 (Manning's global calibration), & #212 (Manning's local calibration override)
