### ISSUE TITLE
[3pt] Compare NWS stage to HAND stage

### ISSUE THREAD

**Issue by TrevorGrout-NOAA** [NOAA-OWP/cahaba#251]
Per FS
Do we calculate the average HAND Thalweg Elevation for each river segment? If so, it'd be interesting to take NWS Flood Stage, convert to Flood Water Surface Elevation, and then subtract HAND Thalweg Elevation from Flood Water Surface Elevation to determine HAND value for NWS Flood Stage. Perhaps worth testing in next iteration of AHPS FIM Libraries.

**Comment by BradfordBates-NOAA** [comment]
@TrevorGrout-NOAA Can this be closed?

**Comment by TrevorGrout-NOAA** [comment]
@BradfordBates-NOAA Yeah this is essentially what we did in the Crane method.
