### ISSUE TITLE
[1pt] Ensure evaluation scripts can easily process data in previous_fim and outputs

### ISSUE THREAD

**Issue by BrianAvant-NOAA** [NOAA-OWP/cahaba#259]
Update the path for the `-b` arg  in `aggregate_metrics.py` so that it can access `previous_fim` or `outputs` folders

The current configuration requires moving the outputs to different directories when caching metrics. This could also be added to the `cache_metrics.py` workflow to consolidate the evaluation process.

**Comment by BradfordBates-NOAA** [comment]
Related to #258
