### ISSUE TITLE
[9pt] Add Eval Capabilities to the API Service

### ISSUE THREAD

**Issue by nickchadwick-noaa** [NOAA-OWP/cahaba#264]
TBD

**Comment by BrianAvant-NOAA** [comment]
@nickchadwick-noaa @TrevorGrout-NOAA @BradfordBates-NOAA 

After discussing with the team, we have determined the API evaluation configuration we would like to see.
This configuration consists of a single button that does the following:
- [ ] uses the latest dev branch
- [ ] uses the calibrated parameters file
- [ ] runs `fim_run.sh` for both MS and FR for the entire NWM domain on a HUC8 scale using the designated huc lists (included_huc8.lst/included_huc8_ms.lst)

- [ ] runs `aggregate_fim_outputs.py` with the `-v` arg
- [ ] runs `synthesize_test_cases.py` 
- [ ] runs categorical fim (workflow still in progress)
- [ ] moves `aggregate_fim_outputs` and `catfim_library.shp` to viz output location
- [ ] moves evaluation metric outputs to VM

**Comment by TrevorGrout-NOAA** [comment]
![image](https://user-images.githubusercontent.com/69653333/113589557-1a8f6d00-95f7-11eb-8524-b85a52560bf8.png)

**Comment by TrevorGrout-NOAA** [comment]
Example call:

After `synthesize_test_cases.py` is run copy the output `all_official_versions.csv` to: ```/data/test_cases/metrics_library/all_official_versions.csv```

Then run evaluation plots (with -sp argument)
```eval_plots.py -m /data/test_cases/metrics_library/all_official_versions.csv -w /data/test_cases/metrics_library/all_official_versions_viz  -v 3_0_9_0_ms_c <newest_version> -sp```

Copy entire workspace directory (-w) back to development vm 

Then run CatFIM:
```generate_categorical_fim.py -f <newest_version> -j number_of_jobs```

**generate_categorical_fim.py looks in the `previous_fim` directory for a folder named <newest_version>**

Copy the files shown to `/data/catfim/<newest_version>` on the development vm.
![image](https://user-images.githubusercontent.com/69653333/113589557-1a8f6d00-95f7-11eb-8524-b85a52560bf8.png)

**Comment by nickchadwick-noaa** [comment]
All of the eval and catFIM capabilities have been added to the "Release" feature on the FIM API. See #373 for more details.
