### ISSUE TITLE
[8pt] Diagnose NWC HAND FIM Incorrect Rating Curve in Southeast Sites (Vlab #88478 and #88488)

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/cahaba#273]
This is for FIM version 3.0.0.3 (which has been updated).

From Kelly Godsey:

The HAND FIMs for three sites in South Georgia (HRAG1, VDSG1, and QUTG1) are using rating curves without applying the correct adjustments to match the datum used by the NWS. These three sites are part of the Suwannee Basin and all stations within the Suwannee Basin changed to report water surface height above sea level in 2015. So for the HAND FIMs at these sites, referencing the USGS rating curve without applying the necessary correction, results in depiction of flooding from a flow that is unrealistic at each specified category. In the attached image for VDSG1, you can note a couple of things, 1) very little variation between the flood areas at the four flood categories, but more importantly, note the model specified flow of over 277kcfs. Simply not possible - and a product of not applying the correction for stage reporting to the rating curve. The NRLDB rating for these three sites would likely produce a much better result.

Additionally - there may be other errors throughout the Suwannee Basin as the NWS uses NAVD88 as the datum for all Suwannee sites in Florida, whereas the USGS still may be referencing NGVD29 as their primary datum. However, in Florida, the difference would not be as dramatic, as the Florida sites have always been on a sea level reporting system. The shift from NGVD29 to NAVD88 in this portion of Florida is generally between -0.6ft and -0.9 ft.

![image](https://user-images.githubusercontent.com/69594899/108878195-9f817280-75c5-11eb-93dc-dddb9e469e6d.png)

**Comment by BradfordBates-NOAA** [comment]
More info from Kelly (88488): 

After seeing the rating curve issues at 3 South Georgia sites (ticket #88478), I went ahead and checked the entirety of the Suwannee basin (forecast points only) and there are several rating curve issues that are affecting the HAND FIMs to the point evaluations cannot be completed at most sites due to significant overflooding.

In Georgia - Sites HRAG1, VDSG1, QUTG1, and STNG1 all share the same issue explained in ticket #88478

In Florida, it was more than just a NGVD29 to NAVD88 conversion issue as some of the older stations are using separate gage datums, thus conversions to current NWS levels are more significant. All sites in the Suwannee Basin in Florida report water surface height above sea level in NAVD88.

WSPF1 - Mismatch between NGVD29 and NAVD88. NAVD88 is 0.83 ft lower at this gage
LIKF1 - Mismatch between NGVD29 and NAVD88. NAVD88 is 0.71 ft lower at this gage
PINF1 - Mismatch between NWS stage and USGS stage. NWS stage is 46.48 ft higher at this gage than USGS gage height.
ELLF1 - Mismatch between NWS stage and USGS stage. NWS stage is 26.5 ft higher at this gage than USGS gage height.
DOUF1 - Mismatch between NGVD29 and NAVD88. NAVD88 is 0.68 ft lower at this gage.
LURF1 - Mismatch between NGVD29 and NAVD88. NAVD88 is 0.67 ft lower at this gage.
BFDF1 - Mismatch between NWS stage and USGS stage. NWS stage is 4.06 ft higher at this gage than USGS gage height.
RCKF1 - Mismatch between NGVD29 and NAVD88. NAVD88 is 0.7 ft lower at this gage.
WCXF1 - Mismatch between NWS stage and USGS stage. NWS stage is -1.18 ft lower at this gage than the USGS gage height.
MTSF1 - Flow from NRLDB so no issues detected with rating curves for HAND FIM - Will evaluate accuracy of flood depiction.
FWBF1 - Flow from NRLDB so no issues detected with rating curves for HAND FIM - Will evaluate accuracy of flood depiction.
WORF1 - Mismatch between NWS stage and USGs stage. NWS stage is 41.91 ft higher at this gage than USGS gage height.
OLPF1 - USGS = NWS at this site, so no rating issues detective for HAND FIM - Will evaluate accuracy of flood depiction.
HSPF1 - Flow from NRLDB so no issues detected with rating curves for HAND FIM - Will evaluate accuracy of flood depiction.
FWHF1 - Mismatch between NWS stage and USGS stage. NWS stage is 20.05 ft higher at this gage than USGS gage height.
TREF1 - Flow from NRLDB so no issues detected with rating curves for HAND FIM - Will evaluate accuracy of flood depiction.
FTWF1 - Flow from NRLDB so no issues detected with rating curves for HAND FIM - Will evaluate accuracy of flood depiction.

![image](https://user-images.githubusercontent.com/69594899/108884103-d22e6980-75cb-11eb-897c-e4cfb9b93825.png)

**Comment by BradfordBates-NOAA** [comment]
@TrevorGrout-NOAA Can you please respond to the Vlab ticket with this information? I will reassign to you.

**Comment by TrevorGrout-NOAA** [comment]
I have created a github ticket to perform a check on whether usgs calculated flows are all null, if so then use nws.
https://github.com/NOAA-OWP/cahaba/issues/400
