### ISSUE TITLE
[8pt] Convert CatFIM pipeline to open source

### ISSUE THREAD

**Issue by BrianAvant-NOAA** [NOAA-OWP/cahaba#279]
Convert ahps libraries pipeline to open source and integrate into the Cahaba repo.

- Convert arcpy dependent script that generates the CatFIM layer `mosaic_ahps_libraries.py`
   - [ ] additional files are used by that script (point files with attributes that are joined to the dissolved layer) and may need to be converted as well
   - [ ] The final layer needs to be dissolved by "ahps_lid;magnitude;version;huc"

- optimize `generate_categorical_fim.py` 
   - [ ] Add a function called `post_process_cat_fim_for_viz()` that calls `mosaic_ahps_libraries.py`
   - [ ] Add "version" (-v) as an arg to allow population of the version attribute
   - [ ] Final output must be feature class in geodatabase (using a template GDB)
   - [ ] Parallelize flood category processing

**Comment by BradfordBates-NOAA** [comment]
Hey @BrianAvant-NOAA I don't see a reason to have `post_process_cat_fim_for_viz()` call `mosaic_ahps_libraries.py`. I think we can deprecate mosaic_ahps_libraries.py and put all of its logic (after converting to open source) into `post_process_cat_fim_for_viz()`. Thoughts?

**Comment by BrianAvant-NOAA** [comment]
> 
> 
> Hey @BrianAvant-NOAA I don't see a reason to have `post_process_cat_fim_for_viz()` call `mosaic_ahps_libraries.py`. I think we can deprecate `mosaic_ahps_libraries.py` and put all of its logic (after converting to open source) into `post_process_cat_fim_for_viz()`. Thoughts?

That is more or less what I meant. I will reach out for feedback before I submit a PR.
