### ISSUE TITLE
[5pt] Many locations have the FIM only downstream or upstream (Vlab #89147)

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/cahaba#299]
From Brent Bower:

"The following list of RFPs have the FIM plygons in the worng place; only at or below the gage and not upstream of the gage. gflw1, pilw1, mrow1, glbw1, spew1, ffxw1, dsrw1, bcdw1, pacw1, neww1, dotw1, satw1, elww1, drsw1. These next RFPs have the FIM polygons upstream only but ends just above or at the gage. crpw1. They are suposed to be 10 miles upstream and downstream."

**Comment by TrevorGrout-NOAA** [comment]
Although I haven't investigated these specific sites there could be a couple reasons for this general behavior. 
All headwater sites (no upstream AHPS points further upstream) will have mapping that will end at the site location as our mainstems streams filter doesn't extend further upstream. We tried to alleviate this (but probably not very much) by including in our mainstems filter all segments downstream of designated headwater usgs gages (regardless if they were associated with ahps site or not). 
As far as downstream mapping the huc boundary serves as a cutoff for the mapping. So if a site is less than 10 miles from the HUC boundary then mapping will end at the boundary. We should probably investigate if there is a way we can resolve this as it probably affects a fair number of sites.

Finally, there could be missing mapping if selected mainstem segments are designated as waterbodies. This could affect mapping in upstream or downstream direction if a waterbody is in the vicinity.

**Comment by BradfordBates-NOAA** [comment]
At or below the gage, not upstream of the gage:

- gflw1: No gages present in upstream portion of HUC8
- pilw1:
- mrow1:
- glbw1:
- spew1
- ffxw1
- dsrw1
- bcdw1
- pacw1
- neww1
- dotw1
- satw1
- elww1
- drsw1
