### ISSUE TITLE
[5pt] Incorrect geometries in CatFIM merged layer

### ISSUE THREAD

**Issue by TrevorGrout-NOAA** [NOAA-OWP/cahaba#318]
Additionally, there appears to be another issue with some sites/thresholds not appearing in correct location/having incorrect (and incomplete) geometry when compared to the grids. For example, id8s2 -record threshold-huc 10160009 and sfrw4-record-threshold-14040107. 

The CatFIM process was run 2 times and the same issue remained.

**Comment by BradfordBates-NOAA** [comment]
@TrevorGrout-NOAA @BrianAvant-NOAA Is this still an issue?
