### ISSUE TITLE
[9pt] Investigate OS options for ras2fim

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/cahaba#349]

**Comment by nickchadwick-noaa** [comment]
Hey @AndyCarter-NOAA , if you can update this ticket with how the ble2fim currently runs for you, I can look into a docker solution for it. If you could include the packages used, the OS, etc, that'd be great.

**Comment by AndyCarter-NOAA** [comment]
BLE2FIM

Python 3.8.5

Python libraries:
   datetime
   fiona 
   geopandas
   h5py
   matplotlib
   numpy
   os
   pandas
   rasterio
   re
   scipy
   shapely
   shutil
   time
   win32com.client
   xarray

Software Installed:
   HEC-RAS v 5.0.7  (https://www.hec.usace.army.mil/software/hec-ras/download.aspx) - Windows Version as Linux version does not have the same capabilities.  This also includes the API of HEC-RAS which is used by the win32com libarary.

**Comment by nickchadwick-noaa** [comment]
After extensive research, it seems that a Linux-based Docker solution will not be viable for this (due to the HEC-RAS API is Windows only and emulating that on a Linux host is not really possible). We will need to get a Windows machine to be able to run this.

**Comment by RobHanna-NOAA** [comment]
Update: I thought I found an update for hecras 6 .1 that works with linux. But, it may not be true quite yet:
ie) Jim response: It's not the compute engine but the ras interface (hec = win32com.client.Dispatch("RAS60.HECRASController") that constructs the calls/plan files that the compute engine is running over that necessitates the windows environment.
