### ISSUE TITLE
[3pt] multiprocessing bug in synthesize_test_cases.py

### ISSUE THREAD

**Issue by BrianAvant-NOAA** [NOAA-OWP/cahaba#351]
synthesize_test_cases.py gets hung up when multiprocessing eval sites and never finishes running.

## Current behavior
The script runs for a while and then gets hung up without throwing an error. Container CPU % drops to zero and several GB of memory are being used while the script waits indefinitely.

**Comment by BradfordBates-NOAA** [comment]
This might not be a bug, it might be a memory issue or data issue, we can investigate

**Comment by BradfordBates-NOAA** [comment]
@BrianAvant-NOAA @RyanSpies-NOAA I did some digging and this is a known issue with the `multiprocessing` library, but the good news is that there seems to be a workaround. I'll have to make some time to implement.

In the meantime, with `synthesize_test_cases.py`, if the process is hung, simply killing and restarting the SAME process will allow the metrics CSV to be produced.

**Comment by BradfordBates-NOAA** [comment]
https://pythonspeed.com/articles/python-multiprocessing/
