### ISSUE TITLE
[1pt] Files not saving when using production argument

### ISSUE THREAD

**Issue by TrevorGrout-NOAA** [NOAA-OWP/cahaba#360]
Some files, such as the usgs_elev_table.csv are not saving when using the -p flag in fim_run. Other files are not saving either.
## Current behavior
![image](https://user-images.githubusercontent.com/69653333/115072493-4ba45300-9ebd-11eb-94d6-072311931c5f.png)

**Comment by BrianAvant-NOAA** [comment]
@TrevorGrout-NOAA can this ticket be closed?
