### ISSUE TITLE
[1pt] Synthesize test cases skipping threshold categories

### ISSUE THREAD

**Issue by TrevorGrout-NOAA** [NOAA-OWP/cahaba#369]
Synthesize test cases appears to be skipping minor and moderate flood categories for v 3.0.15.2 for site camn4.  These minor and moderate categories were scored for v3.0.9.0. At least metrics are contained in the all_official_versions.csv. The benchmark data hasn't changed between these two versions.

## Current behavior
![image](https://user-images.githubusercontent.com/69653333/116259480-730be300-a73b-11eb-82b4-c9315262b596.png)

Screenshot of all_official_versions.csv. The Major category has no CSI, no flow file was supplied. Note how v3.0.15.2 has only action measured
## Steps to replicate behavior (include URLs)

1.

**Comment by BrianAvant-NOAA** [comment]
I'll add to this ticket the multiple print statements for some sites. An example is nws lid `kwpm7` in HUC 10300101. `synthesize_test_cases.py` prints `Evaluating performance at kwpm7` several times in the moderate and major thresholds. I'm not sure if it is an issue with the logging outputs or if it is actually running thresholds multiple times.
