### ISSUE TITLE
[13pt] Write code in feature branch to produce CatFIM with alternative method (Crane method)

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/cahaba#387]
Use HAND SRCs to back-calculate the flow required to yield the official AHPS stage, then apply that same flow 5 miles up and downstream of point. 

Create new outputs with different filename to distinguish from original CatFIM method.

**Comment by TrevorGrout-NOAA** [comment]
![image](https://user-images.githubusercontent.com/69653333/119176015-2f518400-ba30-11eb-9847-a7f4ddd8c61a.png)

I believe this graphic illustrates the idea. I think if we break it down into these steps:
Step 1: Get Threshold Water Surface Elevation (action stage + gage datum)
Step 2: Get HAND stage (action water surface elevation - HAND datum)
Step 3: Get HAND flow (Use rating curve to get flow corresponding to HAND stage)
Step 4: Apply flow to all NWM segments (10 mi upstream/downstream)
