### ISSUE TITLE
[5pt] Scrape and blend terrain sources to support ras2fim

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/cahaba#389]

**Comment by BradfordBates-NOAA** [comment]
@AndyCarter-NOAA Please paste your findings here and close this ticket.

**Comment by AndyCarter-NOAA** [comment]
The AWS terrain scraping routine is working and has been sent to the USACE HEC (which they requested).  There was interest is using the Cloud Optimized GeoTIFFs of the "per collection" data of the 3DEP bare earth DEM's.  Per an email from Dr. Jason Stoker (USGS), these data are not staged as "seamless" cloud enabled terrain making programmatic compositing difficult.  Rather, an Entwine to DEM workflow is the only viable work around.  This is slow as 1 sq mile take about 3 to 4 minutes to obtain.
