### ISSUE TITLE
[9pt] FIM API Refactor and Clean up

### ISSUE THREAD

**Issue by nickchadwick-noaa** [NOAA-OWP/cahaba#391]

**Comment by BradfordBates-NOAA** [comment]
@nickchadwick-noaa Can you provide more info as to what is being refactored?

**Comment by BradfordBates-NOAA** [comment]
@nickchadwick-noaa Is this still relevant?

**Comment by nickchadwick-noaa** [comment]
No I think this can just be closed, I'll create a new ticket if there are some specific things I find needing to be cleaned up.
