### ISSUE TITLE
[5pt] FIM Run Memory Profiling

### ISSUE THREAD

**Issue by nickchadwick-noaa** [NOAA-OWP/cahaba#392]
Wire up a memory profiling python module throughout the `run_by_unit` script to determine where any bottlenecks are in the code.

**Comment by BradfordBates-NOAA** [comment]
@nickchadwick-noaa Can we make this functionality standard such that `fim_run.sh`

**Comment by BradfordBates-NOAA** [comment]
Closed by accident--reopened.
