### ISSUE TITLE
[8pt] Create post-processing tool to vary Manning's n for channel vs. floodplain

### ISSUE THREAD

**Issue by RyanSpies-NOAA** [NOAA-OWP/cahaba#419]
Develop code to vary the Manning's n value for in-channel vs. out-of-channel. Ingest the bankfull detection data in the src_full_crosswalked_bankfull.csv to determine break point and calculate new discharge values using Manning's equation. We'll need to explore best approach for estimating appropriate in-channel Manning's n as well as smoothing/interpolating the roughness curve.

**Comment by frsalas-noaa** [comment]
Do we need a separate card to reflect the calibration activity associated with this new capability? Below is what I'd like to test:

- Use 0.06 as default within channel and our old calibrated values (~0.11) out of channel
- Test draft NWM v3.0 routeLink Mannings for in channel and out of channel (these Mannings derived from CU/NCAR JTTI project for in channel and landuse for out of channel)
- Test draft NWM v3.0 routeLink Mannings for in channel and our calibrated values (~0.11) out of channel

**Comment by RyanSpies-NOAA** [comment]
Example SRC plot:
![18480028_vmann](https://user-images.githubusercontent.com/69868854/139719328-1dbadc93-678e-4166-9a38-9dc4a363e583.png)
