### ISSUE TITLE
[2pt] Replace clipping rasters by HUC boundary with filter method

### ISSUE THREAD

**Issue by BrianAvant-NOAA** [NOAA-OWP/cahaba#42]
This is a subtask of #4. The boundaries of the WBD dataset do not represent the extent of the rem, slope, and catchment layers. 

## Current behavior
Catchment layers on the outer boundary of the unit HUC are being clipped out in run_by_unit.sh. This creates gaps between HUCs of the same unit size. This also causes inconsistency in area between different HUC units.

## Expected behavior
The catchments can be subset using unique HydroIDs instead and the resulting catchment boundary can be used to define the raster extents.

## Steps to replicate behavior (include URLs)

1.

## Screenshots

![image](https://user-images.githubusercontent.com/20129718/93939640-b8bd8480-fcf0-11ea-8862-9a1b4f99a8e7.png)
![image](https://user-images.githubusercontent.com/20129718/93939930-3e413480-fcf1-11ea-9355-5189820b000f.png)

**Comment by frsalas-noaa** [comment]
Can we close this one?
