### ISSUE TITLE
[15pt] Develop workflow to apply and evaluate user-provided SRC modifications to downstream & upstream catchments

### ISSUE THREAD

**Issue by RyanSpies-NOAA** [NOAA-OWP/cahaba#463]
Use the Manning's n modifications that we calculated from locations where users provided FIM and discharge observations to apply corrections to downstream/upstream catchments. This is a follow-on task to #436
Questions:
- how far upstream/downstream should we allow the changes?
- should we use the modified roughness from the nearest hydroid or featureid?

**Comment by BradfordBates-NOAA** [comment]
@RyanSpies-NOAA Perhaps this ticket title could be changed to "[15pt] Develop workflow to apply **and evaluate** user-provided SRC modifications to downstream catchments #463" to track the evaluation work needed before merging.
