### ISSUE TITLE
[5pt] Modify feature_id attribute extraction for usgs_gage_crosswalk.py

### ISSUE THREAD

**Issue by RyanSpies-NOAA** [NOAA-OWP/cahaba#498]
usgs_gage_crosswalk.py currently crosswalks USGS gage points to the hydrofabric "feature_id" using a spatial join with the hydroid catchment polygon layer. This can result in attributing the wrong feature_id when the gage point resides near the boundary of hydroids. Suggest using the USGS gage snapped to the channel/thalweg before performing the sjoin to help avoid this issue.

**Comment by CarsonPruitt-NOAA** [comment]
The `feature_id` mismatch has been traced back to an out-of-date AHPS site dataset. Catchments that have AHPS sites will use its attribute table in the crosswalk and will produce erroneous `HydroID` -- `feature_id` pairs, which will be passed into the `hydroTable.csv` output.
