### ISSUE TITLE
[1pt] Update Docker Image

### ISSUE THREAD

**Issue by BrianAvant-NOAA** [NOAA-OWP/cahaba#56]
Docker Image dev_20200820_56e973af needs a newer version of fiona.

## Current behavior
The current docker image has fiona version '1.8.13.post1' which does not support the  mode='a' argument when writing a Geopandas GeoDataFrame to a file.

## Expected behavior
A new docker image with fiona version '1.8.17' fixes this bug.

## Steps to replicate behavior (include URLs)

1.

**Comment by RyanMcCarthy-NOAA** [comment]
@nickchadwick-noaa  assigning this to you as it is related to #57 .

**Comment by BrianAvant-NOAA** [comment]
confirmed that the new image has fiona version '1.8.17'

**Comment by nickchadwick-noaa** [comment]
Awesome. If you could review and approve the linked pull request I'll go ahead and merge it in sometime today.
