### ISSUE TITLE
[2pt] Replace requirements.txt with Pipfile

### ISSUE THREAD

**Issue by RyanMcCarthy-NOAA** [NOAA-OWP/cahaba#57]
The python community is moving away from requirements.txt to [Pipenv](https://realpython.com/pipenv-guide/). Should be simple enough to convert and add to the docker image.

**Comment by RyanMcCarthy-NOAA** [comment]
@nickchadwick-noaa this is ready to test/merge whenever you're ready.

**Comment by nickchadwick-noaa** [comment]
Thanks @RyanMcCarthy-NOAA , I'll be looking at this soon to merge into both Dockerfiles.
