### ISSUE TITLE
[4pt] Add filter option to test_run_case.py and inundation.py

### ISSUE THREAD

**Issue by BrianAvant-NOAA** [NOAA-OWP/cahaba#59]
Add option in inundation.py to use fossid instead of WBD boundary

## Current behavior
Inundation.py currently uses the WBD geometry to mask the rem and catchment input rasters. This method cuts out part of the catchment boundary. This method also contributes to the scoring discrepancy between HUC scales by including information from adjacent HUCs.

## Expected behavior
A similar method addressed in issue #42 can be used to subset these rasters without losing information. This method will not work for legacy versions of FIM (v1 and v2.x) so an additional argument will need to be added to accommodate both.

## Steps to replicate behavior (include URLs)

Add an argument to run_test_case.py and inundation.py for 'legacy' or 'dev' FIM version. legacy version uses the current WBD boundary method and can be used to compare between legacy and dev FIMs. dev version is used to compare versions after FIM v2. The catchment polygon version will also be passed in order to mask the rem and catchment rasters. 

## Screenshots

![image](https://user-images.githubusercontent.com/20129718/94740396-36f4d900-0338-11eb-83d2-d18ac26691ae.png)

**Comment by frsalas-noaa** [comment]
Can we close this ticket?
