### ISSUE TITLE
[13pt] API Service to automate FIM 3 runs on Production Machines

### ISSUE THREAD

**Issue by nickchadwick-noaa** [NOAA-OWP/cahaba#60]
In order to leverage more than one of the production machines in an automated manner, and API needs to be developed that will take a FIM run request, split the work between the multiple machines, start the docker containers on each machine, then merge the desired results back together in a specified destination.

The system would consist of 2 parts:

- A service that sits on each production node that receives requests and starts the docker containers.
- A "frontend" API that takes the request from the user, splits up the work, and distributes it to each of the services on the production nodes. This frontend API should also be displaying a progress bar for the current work on each machine.

**Comment by frsalas-noaa** [comment]
Documenting here one of the use cases: 

Allow developers to take code in dev feature branch and run FIM v3.X workflow and test cases over numerous HUCs on prod machines. Return specified outputs to dev machine for further analysis.
