### ISSUE TITLE
[2pt] Investigate method to populate BLE flows for each NWM segment

### ISSUE THREAD

**Issue by TrevorGrout-NOAA** [NOAA-OWP/cahaba#86]
Currently, BLE cross sections are intersected against NWM streams and flows assigned to NWM segments. In some cases XS from BLEs are too far apart to intersect all NWM segments. This causes gaps in mapping. Investigate if flow files can be populated so that all NWM segments have a flow assigned. This affects both FIM 2 and FIM 3, but affects the mapping in different locations depending on how the catchments are made.

**Comment by BradfordBates-NOAA** [comment]
@TrevorGrout-NOAA Is this still relevant?
