### ISSUE TITLE
[8pt] Create "janitor" script in Python to delete all unnecessary-for-inundation files from the fim_run.sh output directory.

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/cahaba#88]
There are several intermediate files produced by fim_run.sh. The majority of these files are not necessary for inundation mapping. This takes up storage space. The janitor script will clear out these files. The script would be called at the very end of run_by_unit.sh and a flag will be added to fim_run.sh to use or not use this feature.

**Comment by BradfordBates-NOAA** [comment]
This is related to issue #94

**Comment by nickchadwick-noaa** [comment]
If we could start a discussion here of exactly what files should be whitelisted and which ones could be deleted after the fim_run process, I can start putting this script together to do so.

**Comment by BradfordBates-NOAA** [comment]
- rem_zeroed_masked.tif
- gw_catchments_reaches_filtered_addedAttributes_crosswalked.gpkg
- gw_catchments_reaches_filtered_addedAttributes.tif
- hydroTable.csv
- src.json

**Comment by nickchadwick-noaa** [comment]
And since #94 is related to this, should that issue be addressed first so that I don't have to alter this whitelisting later?

**Comment by BradfordBates-NOAA** [comment]
I was thinking that the janitor script could also be responsible for addressing #94. We could simply rename the whitelisted files according to viz requirements, or duplicate the files and name the duplicates according to viz requirements.

**Comment by nickchadwick-noaa** [comment]
That could possible work, but then it could be confusing for someone who is working on a module and not realizing that the files are being renamed after the fact.

Kind of a nitpicky thing, but if we were to follow this pattern for renaming even more files in the future I can see it being confusing.

Is there any reason for not wanting to change the name at the source as opposed to renaming it after?

**Comment by BradfordBates-NOAA** [comment]
Rationale for renaming after is to 1) reduce disruption and possible breaks in peoples' fim_run.sh runs, 2) the long names are helpful in the dev environment.

Think of the renaming or duplication as post-processing.

**Comment by nickchadwick-noaa** [comment]
That's fair, I'll go ahead and start on the janitor script and implement the renaming from #94 within it.

**Comment by nickchadwick-noaa** [comment]
So this "Janitor" script has been implemented as a "output_cleanup" module at the end of the `run_by_unit.sh` script. This module will handle any whitelisting or renaming of outputs, as well as any post-processing that needs to happen to the outputs on the HUC level.

With this new module, the following option flags have been added to the `fim_run.sh` script:

- `-p/--production`, this will result in only saving only the following files:

  - `rem_zeroed_masked.tif`
  - `gw_catchments_reaches_filtered_addedAttributes_crosswalked.gpkg`
  - `gw_catchments_reaches_filtered_addedAttributes.tif`
  - `hydroTable.csv`
  - `src.json`

- `-v/--viz`, this will result in only saving only the following files:

  - `rem_zeroed_masked.tif` (renamed to `hand_grid_<huc_code>.tif`)
  - `gw_catchments_reaches_filtered_addedAttributes.tif` (renamed to `catchments_<huc_code>.tif`)
  - `src.json` (renamed to `rating_curves_<huc_code>.json`)

  Additionally, the `nwm_feature_id`'s are added to the `src.json` file when this option is used.

- `-w/--whitelist`, any addition files you wanna keep in a production(`-p`) or viz(`-v`) runs.


This covers everything in this issue, #94, and most of #111 (aside from aggregating the HUC8 data into HUC6 data which will have to be a whole other script of its own).

Does this cover everything?
