### ISSUE TITLE
Data gathering (including scripts) and preprocessing for AHPS analysis

### ISSUE THREAD

**Issue by TrevorGrout-NOAA** [NOAA-OWP/cahaba#91]
For evaluation of AHPS sites, a number of datasets must be brought together and formatted. Write scripts as needed to automate as much of this process as possible. Get all files/datasets/scripts ready for so that we can:
1) evaluate all ahps locations that have detailed fim libraries.
2) Use FIM 3 to create inundation maps for action/minor/moderate/major flood categories at all ahps locations.

**Comment by frsalas-noaa** [comment]
Suggest we break this up into smaller tasks. Perhaps this becomes the overarching agile story with smaller tasks feeding into this as separate cards.
