### ISSUE TITLE
[3pt] Simplify names of necessary-for-inundation files

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/cahaba#94]
For example, change "gw_catchments_reaches_filtered_addedAttributes.tif" to "catchments.tif"

**Comment by BradfordBates-NOAA** [comment]
@nickchadwick-noaa please get with @LauraKeys-NOAA and @CoreyKrewson-NOAA to decide on these file names.

**Comment by nickchadwick-noaa** [comment]
This issue is being addressed in #88
