### ISSUE TITLE
[13pt] Implement consistent HydroID between MS and FR configuration

### ISSUE THREAD

**Issue by TrevorGrout-NOAA** [NOAA-OWP/cahaba#97]
Implement a consistent HydroID for catchments between MS and FR configuration. Currently there are two sets of HydroIDs between MS and FR.  Estimated pts may need to be modified as this ticket is being worked on.

**Comment by RyanSpies-NOAA** [comment]
We have modified the goal of this task after discussions with the viz team. I will close this card to align with the sprint end date. I've opened a new card (#221) to perform the new code modifications, final documentation, and pull request preparation for this task.
